# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: engage@kbase.us
author_name: KBase
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: berdl-jupyterlab-coreui
project_short_description: A JupyterLab extension providing tree browser and branding
    for KBase CDM JupyterLab.
python_name: berdl_jupyterlab_coreui
repository: https://github.com/kbaseincubator/BERDL_JupyterLab_CoreUI
test: true

